#spring configuration
server:
  error:
    include-stacktrace: never

spring:
  #h2 database configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  #Spring DataSource configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true